source 'http://rubygems.org'

gem 'rails', '3.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql', '2.8.1'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'jquery-rails', "~>0.2"
gem 'gravatar_image_tag', '0.1.0'

# tests without db
gem 'activerecord-nulldb-adapter'

gem 'devise'
gem 'cancan'

gem 'will_paginate', '~> 3.0.pre2'
gem 'ruby_parser', '2.0.5'
gem 'ruby2ruby'
gem 'prawn'
gem 'prawn_rails'
gem 'rack-raw-upload'
#gem 'spawn'
#gem 'pdfkit'
# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
gem 'ruby-debug'
#gem 'autotest'
#gem 'autotest-notification'
#gem 'autotest-rails-pure'



group :test do
  gem 'single_test'
  gem 'rspec', '2.2.0'
  #gem 'rspec-rails'
  gem 'webrat' 
end
# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development do
  gem 'rspec-rails', '2.2.1'
end
